name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
  push:
    branches:        
      - '*' 

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install third party dependencies
      run: sudo apt update && sudo apt install build-essential zlib1g-dev libsqlite3-dev libz-dev curl gem ruby unzip p7zip-full unrar-free libgcrypt-dev

    - name: Git Clone LDB
      uses: actions/checkout@v3
      with:
        repository: scanoss/ldb
        ref: master
        path: ldb

    - name: Build LDB
      run: cd ldb && make all && sudo make install && sudo mkdir /var/lib/ldb

    - name: make
      run: make all

    - name: version
      run: echo "::set-output name=version::$(./scanoss -version)"
      id: version

    - name: Test output
      run: |
       echo ${{ steps.version.outputs.version }}

    - name: 'Tar files'
      run: tar czvf scanoss.tar.gz scanoss LICENSES/GPL-2.0-only.txt

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: scanoss-${{ steps.version.outputs.version }}-amd64.tar.gz
        path: |
          scanoss.tar.gz
        retention-days: 5
